#!/usr/bin/env bun

import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"
import { createEncryptPromptsPlugin, generateKeyFragments } from "./encrypt-prompts-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@synsci/script"
import { assertLinuxArm64PageSize } from "./linux-arm64-page-size"
import { nativePackageName } from "./native-targets"
import { buildOptions, headlessAssets } from "./build-options"

const options = buildOptions(process.argv.slice(2))
if (options.headless && Script.release)
  throw new Error("Headless builds are development artifacts; unset OPENSCIENCE_RELEASE")

// Fetch and generate models.dev snapshot. Runtime refreshes stale snapshots
// when current frontier IDs are missing, so avoid inventing model aliases here.
const modelsRaw = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`https://models.dev/api.json`).then((x) => x.text())
const modelsJson = JSON.parse(modelsRaw)

await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${JSON.stringify(modelsJson)} as const\n`,
)
console.log("Generated models-snapshot.ts")

const skipInstall = process.argv.includes("--skip-install")
const artifactSource = process.env.OPENSCIENCE_ARTIFACT_SOURCE?.trim() ?? ""
if (artifactSource && !/^[a-f0-9]{40}$/.test(artifactSource)) {
  throw new Error(
    `OPENSCIENCE_ARTIFACT_SOURCE must be an exact lowercase 40-character Git SHA, received '${artifactSource}'`,
  )
}

await fs.promises.rm(options.output, { recursive: true, force: true })
await $`bun run script/generate-skill-bundle.ts`

// Build the openscience web UI (frontend/workspace) and regenerate the embedded asset
// manifest so the catch-all route in server.ts can serve it locally instead
// of proxying to Vercel. The manifest imports every dist file with
// `with { type: "file" }` so Bun's --compile bundles them into the binary.
//
// `frontend/workspace/package.json` references workspace packages via the `catalog:`
// protocol, which only resolves after `bun install` at the monorepo root. On a
// fresh clone vite's resolver fails with cryptic "Cannot find package" errors
// — run the workspace install if `node_modules` is missing.
const repoRoot = path.resolve(dir, "../..")
const webAppDir = path.resolve(repoRoot, "frontend/workspace")
if (!options.headless) {
  if (!fs.existsSync(path.join(repoRoot, "node_modules")) || !fs.existsSync(path.join(webAppDir, "node_modules"))) {
    console.log("workspace node_modules missing — running bun install at repo root")
    await $`bun install`.cwd(repoRoot)
  }
  console.log("building frontend/workspace (openscience web)")
  await $`VITE_OPENSCIENCE_VERSION=${Script.version} bun run build`.cwd(webAppDir)
  await Bun.file(path.join(webAppDir, "dist", "version.json")).write(
    JSON.stringify({ version: Script.version, channel: Script.channel }, null, 2) + "\n",
  )
  await $`bun run script/generate-web-assets.ts`
}

// Generate encryption key for prompt files (unique per build)
const keyFragments = generateKeyFragments()
const { plugin: encryptPlugin, defines: keyDefines } = createEncryptPromptsPlugin(keyFragments)

const binaries: Record<string, string> = {}
if (!skipInstall && !options.headless) {
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of options.targets) {
  const name = nativePackageName(pkg.name, item)
  console.log(`building ${name}`)
  const output = path.join(options.output, name)
  await fs.promises.mkdir(path.join(output, "bin"), { recursive: true })

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [encryptPlugin, ...(options.headless ? [headlessAssets(dir)] : [])],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: path.join(output, "bin/openscience"),
      execArgv: [`--user-agent=openscience/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/bootstrap.ts"],
    define: {
      ...keyDefines,
      OPENSCIENCE_VERSION: `'${Script.version}'`,
      OPENSCIENCE_CHANNEL: `'${Script.channel}'`,
      OPENSCIENCE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      OPENSCIENCE_PLATFORM_PACKAGE: `'${name}'`,
      OPENSCIENCE_ARTIFACT_SOURCE: JSON.stringify(artifactSource),
    },
  })

  if (item.os === "linux" && item.arch === "arm64") {
    const report = await assertLinuxArm64PageSize(path.join(output, "bin/openscience"))
    console.log(`verified ${name} has ${report.loads} ELF load segments compatible with 64KB-page kernels`)
  }

  await Bun.file(path.join(output, "package.json")).write(
    JSON.stringify(
      {
        name,
        ...(options.headless ? { private: true } : {}),
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
        // Without libc, linux-x64 hosts install all four x64 variants
        // (~750 MB) and glibc/musl selection falls to the bin wrapper.
        ...(item.os === "linux" ? { libc: [item.abi === "musl" ? "musl" : "glibc"] } : {}),
        // npm provenance refuses packages whose repository.url doesn't match
        // the repo the workflow ran from (case-sensitive)
        repository: {
          type: "git",
          url: "git+https://github.com/synthetic-sciences/openscience.git",
        },
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  const checksums: string[] = []
  for (const key of Object.keys(binaries)) {
    const archiveName = key.replace(`${pkg.name}-`, "openscience-") + (key.includes("linux") ? ".tar.gz" : ".zip")
    if (key.includes("linux")) {
      await $`tar -czf ${path.resolve(dir, `dist/${archiveName}`)} *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ${path.resolve(dir, `dist/${archiveName}`)} *`.cwd(`dist/${key}/bin`)
    }
    const bytes = await Bun.file(path.resolve(dir, `dist/${archiveName}`)).arrayBuffer()
    const hash = new Bun.CryptoHasher("sha256").update(bytes).digest("hex")
    checksums.push(`${hash}  ${archiveName}`)
  }
  // sha256sum-compatible manifest; the install script verifies against it
  await Bun.write(path.resolve(dir, "dist/checksums.txt"), checksums.join("\n") + "\n")
}

export { binaries }
