#!/usr/bin/env bun

import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { assertNoRetiredProductSkills, bundleDigest } from "../src/skill/bundle-format"

const file = fileURLToPath(import.meta.url)
const cli = path.resolve(path.dirname(file), "..")
const root = path.join(cli, "skills")
const bundle = path.join(cli, "dist", "skills.tar.gz")
const output = path.join(cli, "src", "skill", "bundled.generated.ts")

async function walk(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const target = path.join(dir, entry.name)
      if (entry.isDirectory()) return walk(target)
      if (entry.isFile()) return [target]
      return []
    }),
  )
  return nested.flat()
}

const files = (await walk(root)).sort()
const data: Record<string, Uint8Array> = {}
const entries: { path: string; bytes: Uint8Array }[] = []
const skills = files.filter((entry) => path.basename(entry) === "SKILL.md").length

for (const entry of files) {
  const rel = path.relative(root, entry).replaceAll("\\", "/")
  const bytes = await Bun.file(entry).bytes()
  data[rel] = bytes
  entries.push({ path: rel, bytes })
}

assertNoRetiredProductSkills(entries)
const digest = bundleDigest(entries)
await fs.mkdir(path.dirname(bundle), { recursive: true })
await Bun.Archive.write(bundle, data, { compress: "gzip", level: 9 })

const spec = path.relative(path.dirname(output), bundle).replaceAll("\\", "/")
const source = [
  "// AUTO-GENERATED by script/generate-skill-bundle.ts — do not edit.",
  "// The tarball is embedded by Bun when building the standalone executable.",
  "// @ts-nocheck",
  `import archive from "${spec.startsWith(".") ? spec : `./${spec}`}" with { type: "file" }`,
  "",
  "export const SKILL_BUNDLE = archive as unknown as string",
  `export const SKILL_BUNDLE_DIGEST = "${digest}"`,
  `export const SKILL_BUNDLE_FILES = ${files.length}`,
  `export const SKILL_BUNDLE_SKILLS = ${skills}`,
  "",
].join("\n")

await Bun.write(output, source)
console.log(`generate-skill-bundle: packed ${skills} skills (${files.length} files) as ${digest.slice(0, 12)}`)
