import { describe, expect, test } from "bun:test"
import path from "node:path"
import { check, files, missing, parse, plan, root, snapshot, tools, usage } from "../../../../tooling/repo/setup"

const none = parse([])

describe("setup flags", () => {
  test("defaults to installing and generating whatever is missing", () => {
    expect(none).toEqual({ web: false, skipWeb: false, skipModels: false, skipInstall: false })
    expect(plan({ flags: none, assets: false, snapshot: false })).toEqual({ install: true, models: true, web: true })
    expect(plan({ flags: none, assets: true, snapshot: true })).toEqual({ install: true, models: false, web: false })
  })

  test("--web rebuilds embedded assets even when present and --skip-* opt out", () => {
    expect(plan({ flags: parse(["--web"]), assets: true, snapshot: true }).web).toBe(true)
    const skipped = plan({
      flags: parse(["--skip-web", "--skip-models", "--skip-install"]),
      assets: false,
      snapshot: false,
    })
    expect(skipped).toEqual({ install: false, models: false, web: false })
  })

  test("rejects unknown and contradictory options with the usage line", () => {
    expect(() => parse(["--verbose"])).toThrow(usage)
    expect(() => parse(["--web", "--skip-web"])).toThrow("exclusive")
  })
})

describe("setup bun check", () => {
  test("accepts the pin silently and any caret-compatible bun with a warning", () => {
    expect(check("1.3.14", "1.3.14")).toBeUndefined()
    expect(check("1.3.20", "1.3.14")).toContain("differs from the pinned bun@1.3.14")
    expect(check("1.4.0", "1.3.14")).toContain("differs")
  })

  test("rejects an older or major-different bun and a missing pin", () => {
    expect(() => check("1.3.13", "1.3.14")).toThrow("needs bun@^1.3.14")
    expect(() => check("2.0.0", "1.3.14")).toThrow("bun-v1.3.14")
    expect(() => check("1.3.14", undefined)).toThrow("packageManager")
  })

  test("uses the pin from the root package.json", async () => {
    const pkg = await Bun.file(path.join(root, "package.json")).json()
    const pin = pkg.packageManager.split("@")[1]
    expect(check(pin, pin)).toBeUndefined()
    expect(() => check(process.versions.bun, pin)).not.toThrow()
  })
})

describe("setup generated files", () => {
  test("reports exactly the documented tools that PATH lacks", () => {
    const missed = missing()
    for (const name of Object.keys(tools)) {
      expect(missed.some((line) => line.startsWith(`${name} is not on PATH`))).toBe(Bun.which(name) === null)
    }
  })

  test("targets the gitignored files the backend imports", async () => {
    const ignore = await Bun.file(path.join(root, "backend/cli/.gitignore")).text()
    expect(ignore).toContain(path.relative(path.join(root, "backend/cli"), files.assets))
    expect(ignore).toContain(path.relative(path.join(root, "backend/cli"), files.snapshot))
  })

  test("writes the snapshot export the runtime imports", () => {
    const module = snapshot({ anthropic: { id: "anthropic" } })
    expect(module).toBe(
      '// Auto-generated by tooling/repo/setup.ts and backend/cli/script/build.ts - do not edit\nexport const snapshot = {"anthropic":{"id":"anthropic"}} as const\n',
    )
  })
})
