#!/usr/bin/env bun
// One-command contributor setup: verify the pinned Bun, warn about missing
// local tooling, install workspace dependencies, and produce the gitignored
// generated files that `bun dev` needs to serve the workspace UI offline.
// Documented in CONTRIBUTING.md; keep the two in sync.

import { $, semver } from "bun"
import fs from "node:fs"
import path from "node:path"

export const root = path.resolve(import.meta.dir, "../..")
export const files = {
  assets: path.join(root, "backend/cli/src/web/assets.generated.ts"),
  snapshot: path.join(root, "backend/cli/src/provider/models-snapshot.ts"),
  version: path.join(root, "frontend/workspace/dist/version.json"),
}

const options = ["--web", "--skip-web", "--skip-models", "--skip-install"] as const
export const usage = `usage: bun run setup [${options.join("] [")}]`

export function parse(argv: string[]) {
  const unknown = argv.filter((arg) => !options.includes(arg as (typeof options)[number]))
  if (unknown.length) throw new Error(`Unknown option ${unknown.join(" ")}\n${usage}`)
  if (argv.includes("--web") && argv.includes("--skip-web"))
    throw new Error(`--web and --skip-web are exclusive\n${usage}`)
  return {
    web: argv.includes("--web"),
    skipWeb: argv.includes("--skip-web"),
    skipModels: argv.includes("--skip-models"),
    skipInstall: argv.includes("--skip-install"),
  }
}

// Same qualifier as tooling/script/src/index.ts and .husky/pre-push: any
// bun@^pinned works, the exact pin is what CI installs.
export function check(actual: string, expected: string | undefined) {
  if (!expected) throw new Error("packageManager field not found in root package.json")
  const range = `^${expected}`
  if (!semver.satisfies(actual, range)) {
    throw new Error(
      `OpenScience needs bun@${range} (packageManager in package.json) but this is bun@${actual}. ` +
        `Install the pin with: curl -fsSL https://bun.sh/install | bash -s "bun-v${expected}"`,
    )
  }
  if (actual === expected) return
  return `bun@${actual} differs from the pinned bun@${expected}; CI and release builds use the pin`
}

export const tools = {
  gitleaks: "the pre-commit hook runs it; install from https://github.com/gitleaks/gitleaks#installing",
  node: "release entrypoints and the desktop shell are Node scripts; install Node 18 or newer",
}

export function missing(which: (name: string) => string | null = Bun.which) {
  return Object.entries(tools)
    .filter(([name]) => !which(name))
    .map(([name, why]) => `${name} is not on PATH: ${why}`)
}

export function plan(input: { flags: ReturnType<typeof parse>; assets: boolean; snapshot: boolean }) {
  return {
    install: !input.flags.skipInstall,
    models: !input.flags.skipModels && !input.snapshot,
    web: !input.flags.skipWeb && (input.flags.web || !input.assets),
  }
}

export function snapshot(catalog: unknown) {
  return `// Auto-generated by tooling/repo/setup.ts and backend/cli/script/build.ts - do not edit\nexport const snapshot = ${JSON.stringify(catalog)} as const\n`
}

async function catalog() {
  const local = process.env.MODELS_DEV_API_JSON
  if (local) return Bun.file(local).json()
  return fetch("https://models.dev/api.json", { signal: AbortSignal.timeout(15_000) })
    .then((res) => {
      if (!res.ok) throw new Error(res.statusText)
      return res.json()
    })
    .catch((error: Error) => {
      console.warn(`setup: could not download the models.dev catalog (${error.message}); skipping the snapshot`)
      console.warn("setup: the runtime fetches the live catalog on first start, so this only matters offline")
    })
}

async function main() {
  const flags = parse(process.argv.slice(2))
  const pkg = await Bun.file(path.join(root, "package.json")).json()
  const drift = check(process.versions.bun, pkg.packageManager?.split("@")[1])
  if (drift) console.warn(`setup: ${drift}`)
  for (const warning of missing()) console.warn(`setup: ${warning}`)

  const steps = plan({ flags, assets: fs.existsSync(files.assets), snapshot: fs.existsSync(files.snapshot) })
  if (steps.install) {
    console.log("setup: bun install --frozen-lockfile")
    await $`bun install --frozen-lockfile`.cwd(root)
  }
  if (steps.models) {
    const data = await catalog()
    if (data) {
      await Bun.write(files.snapshot, snapshot(data))
      console.log(`setup: wrote ${path.relative(root, files.snapshot)}`)
    }
  }
  if (steps.web) {
    console.log("setup: building frontend/workspace and embedding it for `bun dev`")
    await $`bun run build`
      .cwd(path.join(root, "frontend/workspace"))
      .env({ ...process.env, VITE_OPENSCIENCE_VERSION: "local" })
    await Bun.write(files.version, JSON.stringify({ version: "local", channel: "local" }, null, 2) + "\n")
    await $`bun run script/generate-web-assets.ts`.cwd(path.join(root, "backend/cli"))
  }
  if (!steps.web && !flags.skipWeb) console.log("setup: workspace assets already embedded; pass --web to rebuild them")
  console.log("setup: done. Next: `bun dev` opens the workspace, `bun run check` runs the local gates")
}

if (import.meta.main) {
  await main().catch((error: Error) => {
    console.error(`setup: ${error.message}`)
    process.exit(1)
  })
}
