import fs from "node:fs/promises"
import path from "node:path"
import { Global } from "@/global"
import { Installation } from "@/installation"
import { Filesystem } from "@/util/filesystem"
import { FileLease } from "@/util/file-lease"
import { Log } from "@/util/log"
import { directoryDigest } from "./bundle-format"

type Bundle = {
  SKILL_BUNDLE: string
  SKILL_BUNDLE_DIGEST: string
  SKILL_BUNDLE_FILES: number
  SKILL_BUNDLE_SKILLS: number
}

export namespace BundledSkills {
  const log = Log.create({ service: "bundled-skills" })

  async function generated(): Promise<Bundle | undefined> {
    // @ts-ignore generated by script/generate-skill-bundle.ts during release builds
    return import("./bundled.generated").catch(() => undefined)
  }

  type Materialize = { archive: string; digest: string; files: number; skills: number; cache?: string }

  // Project instances share one extraction; the lease also coordinates processes.
  const inflight = new Map<string, Promise<string>>()

  export function materialize(input: Materialize): Promise<string> {
    if (!/^[a-f0-9]{64}$/.test(input.digest)) return Promise.reject(new Error("Invalid bundled skill digest"))
    const base = input.cache ?? path.join(Global.Path.cache, "bundled-skills")
    const key = path.join(base, input.digest)
    const pending = inflight.get(key)
    if (pending) return pending
    const task = extract(input, base).finally(() => inflight.delete(key))
    inflight.set(key, task)
    return task
  }

  async function verified(marker: string, input: Materialize) {
    return Bun.file(marker)
      .json()
      .then((value) => value?.digest === input.digest && value?.files === input.files && value?.skills === input.skills)
      .catch(() => false)
  }

  async function extract(input: Materialize, base: string): Promise<string> {
    const root = path.join(base, input.digest)
    const marker = path.join(root, ".openscience-bundle.json")
    if (await verified(marker, input)) return root

    // Multiple project instances and processes share this content-addressed cache.
    await using lease = await FileLease.acquire(path.join(base, `${input.digest}.lock`), 60_000)
    if (await verified(marker, input)) return root
    const tmp = await fs.mkdtemp(path.join(base, `.${input.digest}.`))
    try {
      const bytes = await Bun.file(input.archive).bytes()
      const count = await new Bun.Archive(bytes).extract(tmp)
      if (count < input.files) {
        throw new Error(`Bundled skill archive is incomplete: expected ${input.files} files, extracted ${count}`)
      }
      const digest = await directoryDigest(tmp)
      if (digest !== input.digest) {
        throw new Error(`Bundled skill archive failed verification: expected ${input.digest}, got ${digest}`)
      }

      for await (const script of new Bun.Glob("**/*.{py,sh,js,ts}").scan({
        cwd: tmp,
        absolute: true,
        onlyFiles: true,
      })) {
        await fs.chmod(script, 0o755).catch(() => {})
      }
      await Bun.write(
        path.join(tmp, ".openscience-bundle.json"),
        JSON.stringify({ digest: input.digest, files: input.files, skills: input.skills }),
      )

      // An older app may still publish the same bundle without taking the lease.
      if (await verified(marker, input)) return root
      await fs.rm(root, { recursive: true, force: true })
      await fs.rename(tmp, root).catch(async (error) => {
        if (await verified(marker, input)) return
        throw error
      })
      return root
    } finally {
      await fs.rm(tmp, { recursive: true, force: true })
    }
  }

  export async function root(): Promise<string | undefined> {
    const local = path.join(import.meta.dir, "../../skills")
    if (Installation.isLocal() && (await Filesystem.isDir(local))) return local

    const bundle = await generated()
    if (!bundle) {
      log.error("compiled release is missing its local skill bundle")
      return
    }

    return materialize({
      archive: bundle.SKILL_BUNDLE,
      digest: bundle.SKILL_BUNDLE_DIGEST,
      files: bundle.SKILL_BUNDLE_FILES,
      skills: bundle.SKILL_BUNDLE_SKILLS,
    })
  }
}
